spring.application.name=hotel
server.port=8092

# Use H2 by default and allow quick DB profile switching.
spring.profiles.default=h2
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
